version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
      - add_ssh_keys:
         fingerprints:
          - "db:37:42:18:f7:a5:a3:f6:0c:ad:c9:f2:99:4e:55:52"
          name: Building SuperRyzen Kernel
          command: |
            wget https://raw.githubusercontent.com/TianWalkzzMiku/SRyzen-CAF/caf/build-start.sh
            bash build-start.sh stable clang
            cd kernel
            wget https://raw.githubusercontent.com/TianWalkzzMiku/SRyzen-CAF/caf/build-dtb.sh
            bash build-dtb.sh a26x clang qpnp
            bash build-dtb.sh lavender clang qpnp
            bash build-dtb.sh tulip clang qpnp
            bash build-dtb.sh whyred clang qpnp
            git apply qti.patch
            bash build-dtb.sh a26x clang qti
            bash build-dtb.sh lavender clang qti
            bash build-dtb.sh tulip clang qti
            bash build-dtb.sh whyred clang qti
            git restore .
            wget https://raw.githubusercontent.com/TianWalkzzMiku/SRyzen-CAF/caf/build.sh
            bash build.sh a26x newcam clang
            bash build.sh a26x oldcam clang
            bash build.sh a26x tencam clang
            bash build.sh lavender newcam clang
            bash build.sh lavender oldcam clang
            bash build.sh tulip newcam clang
            bash build.sh tulip oldcam clang
            bash build.sh whyred newcam clang
            bash build.sh whyred oldcam clang
            git apply oc.patch
            bash build-dtb.sh tulip clang qpnp
            bash build-dtb.sh whyred clang qpnp
            git apply qti.patch
            bash build-dtb.sh tulip clang qti
            bash build-dtb.sh whyred clang qti
            git restore .
            bash build.sh tulip newcam oc clang
            bash build.sh tulip oldcam oc clang
            bash build.sh whyred newcam oc clang
            bash build.sh whyred oldcam oc clang
            wget https://raw.githubusercontent.com/TianWalkzzMiku/SRyzen-CAF/caf/build-final.sh
            bash build-final.sh clang
